version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    depends_on:
      - mysql
    volumes:
      - ../backend:/var/www/html
    env_file:
      - .env
    ports:
      - "${PHP_PORT}:80"
    restart: always
    networks:
      - backend

  mysql:
    image: mysql:8.2
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "${DB_PORT}:80"
    restart: always
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - mysql
    ports:
      - "${PMA_PORT}:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: ${PMA_PORT}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    restart: always
    networks:
      - backend


volumes:
  mysql-data:

networks:
  backend: